USE ROLE SYSADMIN;

-- WAREHOUSE (if you don't have one)
CREATE WAREHOUSE IF NOT EXISTS DBT_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;
-- DATABASE
CREATE DATABASE IF NOT EXISTS DBT_SNOWFLAKE_DEV;
-- SCHEMAS
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.RAW;
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.STAGING;
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS DBT_SNOWFLAKE_DEV.MARTS;


