USE ROLE SYSADMIN;
USE WAREHOUSE DBT_WH;
USE DATABASE DBT_SNOWFLAKE_DEV;
USE SCHEMA RAW;

DESCRIBE INTEGRATION S3_SNOWFLAKE_INTEGRATION;

-- Create file format for CSV
CREATE OR REPLACE FILE FORMAT DBT_SNOWFLAKE_DEV.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', 'N/A', '')
    EMPTY_FIELD_AS_NULL = TRUE
    TRIM_SPACE = TRUE;

-- Create stage for netflix_titles
CREATE OR REPLACE STAGE DBT_SNOWFLAKE_DEV.RAW.S3_NETFLIX_STAGE
    STORAGE_INTEGRATION = S3_SNOWFLAKE_INTEGRATION
    URL = 's3://your bucket name/raw/netflix_titles/'
    FILE_FORMAT = DBT_SNOWFLAKE_DEV.RAW.CSV_FORMAT;

-- Create stage for credits
CREATE OR REPLACE STAGE DBT_SNOWFLAKE_DEV.RAW.S3_CREDITS_STAGE
    STORAGE_INTEGRATION = S3_SNOWFLAKE_INTEGRATION
    URL = 's3://your bucket name/raw/credits/'
    FILE_FORMAT = DBT_SNOWFLAKE_DEV.RAW.CSV_FORMAT;