
USE WAREHOUSE DBT_WH;
USE DATABASE DBT_SNOWFLAKE_DEV;
USE SCHEMA RAW;

-- Load NETFLIX_TITLES
COPY INTO DBT_SNOWFLAKE_DEV.RAW.NETFLIX_TITLES
FROM @DBT_SNOWFLAKE_DEV.RAW.S3_NETFLIX_STAGE
FILE_FORMAT = (FORMAT_NAME = 'DBT_SNOWFLAKE_DEV.RAW.CSV_FORMAT')
ON_ERROR = 'CONTINUE';

-- Load CREDITS
COPY INTO DBT_SNOWFLAKE_DEV.RAW.CREDITS
FROM @DBT_SNOWFLAKE_DEV.RAW.S3_CREDITS_STAGE
FILE_FORMAT = (FORMAT_NAME = 'DBT_SNOWFLAKE_DEV.RAW.CSV_FORMAT')
ON_ERROR = 'CONTINUE';


